### ISSUE TITLE
Thiết kế DB

### ISSUE THREAD

**Issue by duysmile** [duysmile/football-pitch-booking#3]
- [x] Vẽ diagram
- [x] Tạo model

**Comment by ntdo2506** [comment]
### Test nghe

**Comment by Taythaytu0905** [comment]
> * [ ]  Vẽ diagram
> * [ ]  Tạo model

**Comment by ba-p** [comment]
test

**Comment by ba-p** [comment]
![image](https://user-images.githubusercontent.com/60724808/84866609-1fa12100-b0a4-11ea-9ad1-7d936fd99cb9.png)

**Comment by ba-ppp** [comment]
![image](https://user-images.githubusercontent.com/60724808/84866859-845c7b80-b0a4-11ea-921c-4c2e4e708ef4.png)

**Comment by ntdo2506** [comment]
Thêm field đặt cọc nữa e!
Verify là sao e ?

**Comment by ba-ppp** [comment]
verify là chỗ xác nhận email á a

**Comment by ntdo2506** [comment]
> verify là chỗ xác nhận email á a

Mà e nên vẽ theo class diagram ấy

**Comment by ntdo2506** [comment]
![1](https://user-images.githubusercontent.com/56883846/84867283-195f7480-b0a5-11ea-92fa-76bef274e063.jpg)
Như ri nề e

**Comment by ba-ppp** [comment]
> ![1](https://user-images.githubusercontent.com/56883846/84867283-195f7480-b0a5-11ea-92fa-76bef274e063.jpg)
> Như ri nề e

ok a

**Comment by ntdo2506** [comment]
> verify là chỗ xác nhận email á a

a nghĩ cái ni k cần...ta cần xem trạng thái đã đặt hay k đặt thôi isComplete như tham khảo ấy

**Comment by ba-ppp** [comment]
![image](https://user-images.githubusercontent.com/60724808/84874519-e4f0b600-b0ae-11ea-92ac-97f91afbc0f6.png)

**Comment by ntdo2506** [comment]
Price e bỏ qua Yard đi..vì tùy vào max mà sẽ có giá khác nhau chứ không phải giá chung được

**Comment by ba-ppp** [comment]
à e để nhằm chỗ để bên field mới đúng

**Comment by ba-ppp** [comment]
![image](https://user-images.githubusercontent.com/60724808/84875098-b8896980-b0af-11ea-8658-c0e753a8c155.png)

**Comment by ba-ppp** [comment]
ok ch a

**Comment by ntdo2506** [comment]
A nghĩ chỗ timeset nên thêm trạng thái isRent nữa kiểu giờ đó đã thuê hay chưa thuê nữa

**Comment by ba-ppp** [comment]
chỗ đó e đang suy nghĩ là nên để khung giờ sẵn vd: 7 -> 9 luôn hay là sao cũng được á

**Comment by ntdo2506** [comment]
> chỗ đó e đang suy nghĩ là nên để khung giờ sẵn vd: 7 -> 9 luôn hay là sao cũng được á

A nghĩ cũng được nhưng mỗi time sẽ thêm field isRent true là đã đặt false là chưa để mình hiển thị trạng thái lên cho mn xem

**Comment by ba-ppp** [comment]
oke a

**Comment by ba-ppp** [comment]
![image](https://user-images.githubusercontent.com/60724808/84875693-82001e80-b0b0-11ea-8d30-36f1459f937f.png)

**Comment by ba-ppp** [comment]
còn gì nữa hong a

**Comment by ntdo2506** [comment]
> còn gì nữa hong a

e có thể chỗ customer vì sao e bỏ vào owner sẽ khó quản lý là thằng ni thuê sân nào,,sao e k bỏ nó vào order luôn...owner chỉ việc chọn sân và biết ai thuê chứ đi tìm thêm dữ liệu thuê sân nữa thì mệt...e thấy cái a gửi tham khảo ok xong thêm field price với phụ phí vào ấy

**Comment by ba-ppp** [comment]
như v là chỉ cần bỏ customers bên owners là ok ròi a

**Comment by ntdo2506** [comment]
> như v là chỉ cần bỏ customers bên owners là ok ròi a

a vẫn chưa hiểu ý e lắm :))) đợi Duy vào xem rồi tối có gì e giải thích a với...chứ a thấy cái a tham khảo xong thêm field price với phụ phí vào xong rồi...dễ hiểu rõ ràng nữa

**Comment by ba-ppp** [comment]
thì cái tham khảo y chang mà a e thêm phí vô thoi á

**Comment by ntdo2506** [comment]
> thì cái tham khảo y chang mà a e thêm phí vô thoi á

thế bên owner e bỏ field customer đi là ok rồi

**Comment by ba-ppp** [comment]
![image](https://user-images.githubusercontent.com/60724808/84877333-934a2a80-b0b2-11ea-9bb4-c01175edd835.png)

**Comment by ba-ppp** [comment]
> > thì cái tham khảo y chang mà a e thêm phí vô thoi á
> 
> thế bên owner e bỏ field customer đi là ok rồi

thì nãy e nói v mà :))

**Comment by ntdo2506** [comment]
> > > thì cái tham khảo y chang mà a e thêm phí vô thoi á
> > 
> > 
> > thế bên owner e bỏ field customer đi là ok rồi
> 
> thì nãy e nói v mà :))

kkk ok e :3 thế e sửa lại luôn rồi chốt đi e ✌️

**Comment by ba-ppp** [comment]
ở trên đó a

**Comment by ntdo2506** [comment]
> ở trên đó a

ok rồi đó..đợi Duy vào có góp ý gì k..tối ni ae chia nhau ra làm desgin cho rồi :))))

**Comment by ba-ppp** [comment]
ok a

**Comment by duysmile** [comment]
Em góp ý một chút nhé
Đầu tiên là bảng `Owners`:
- Mình thống nhất tên `fields` thay vì `stadiums` luôn cho khỏi nhầm lẫn
- Thường thì doanh thu người ta hay thống kê theo tuần tháng năm, chứ ít khi nào tính tổng từ lúc sinh ra tới mất đi để lưu như này :))) 
- Những cái thông tin chưa cần thiết như avatar thì mình tạm thời chưa dùng đến để đỡ mất thời gian nè.

Rồi tới bảng `Yards`:
- Chỗ `number` mình đổi tên field `name` luôn cho thống nhất, ở đây ý nghĩa là tên sân mà phải ko? Ví dụ sân 5A thì đó là tên sân.
- Chỗ `max` thì mình nên đổi thành `type` cho dễ hiểu, ở đây mình quy định một số loại sân chuẩn thôi.
- Bảng này không nên lưu timeset và orders vì 2 cái này dữ liệu sẽ tăng theo thời gian lên nhiều.

Bảng customer thì mình ko cần dùng luôn vì mình k cho user đăng nhập mà, mọi thông tin của customer mình lưu trong bảng order là được rồi, vì đối với mỗi order thì mình cần thông tin người đặt để nhắc nhở, thu tiền, ... (À em chưa thấy bảng `order` luôn)

Time set thì mình nên chỉ quy định những khung giờ đối với mỗi sân, cái này do owner tạo, ví dụ time: 1h - 2h, ...
Còn mình cần một bảng nữa để lưu những giờ đã đặt sân theo ngày, vì có thể đặt sân trước mà, nếu như dữ liệu bây giờ thì chỉ quản lí được việc đặt sân trong ngày thôi.

Tất cả các dữ liệu liên quan đến owner nên có thêm field owner lưu ownerId để việc query được chính xác.

**Comment by ba-ppp** [comment]
oke a để e sửa lại

**Comment by ba-ppp** [comment]
với cái `timeset` và `order` là e định lưu id của nó thoi chứ k có lưu data dô được k a

**Comment by ba-ppp** [comment]
còn cái doanh thu a định làm như nào dạ a

**Comment by duysmile** [comment]
> với cái `timeset` và `order` là e định lưu id của nó thoi chứ k có lưu data dô được k a

chỗ này trong em không cần lưu trong yard luôn, em cứ tưởng tượng muốn xem lịch đặt sân thì người ta sẽ mở ra một cái lịch, là cái bảng lịch rồi từ cái bảng đó mình sẽ hiển thị ra được thông tin ngày giờ sân, nên là thay vì lưu lịch trong bảng sân, thì mình lưu sân trong bảng lịch :))) 
tương tự với cái order, thì mình lưu yardId vô là đc rồi

**Comment by duysmile** [comment]
> còn cái doanh thu a định làm như nào dạ a

doanh thu tạm thời chưa cần nghĩ nha e, mình sẽ làm từ cái bảng order, nên là xong trước những phần ni rồi mình sẽ làm cái đó sau

**Comment by ba-p** [comment]
![image](https://user-images.githubusercontent.com/60724808/84975100-d0fc9100-b14e-11ea-937f-85c86205c32d.png)

**Comment by ba-ppp** [comment]
![image](https://user-images.githubusercontent.com/60724808/84975446-98a98280-b14f-11ea-8d08-3ef5718a4d1a.png)

**Comment by ba-ppp** [comment]
- Trong `Calendar` thì mỗi index của `date`, `hour`, `orderId` sẽ tương ứng với nhau, còn bên `Day` thì sẽ có `date` sẽ là ngày hiện tại, mỗi ngày sẽ tìm trong  `date` của `Calendar` tương ứng với nó và sẽ tạo render ra `hour` cũng như `orderId`
- Trong `Order` thì `date` là ngày mà người đó nhấn đặt sân còn ngày mà người đó lấy sân sẽ được lưu trong `Calendar`
- Trong `Timeset` thì `start` và `end` là giờ bắt đầu cho thuê và giờ kết thúc thuê, `isEmpty` là sân còn giờ trống hay k

**Comment by duysmile** [comment]
Ok a xem qua rồi, a góp ý chút nhé.
Đầu tiên là bảng owner thì khi query rất ít khi người ta query lấy danh sách sân từ bảng owner nên việc lưu ở đây ko cần thiết.
Chỗ timeset chỉ cần lưu khung giờ được quy định cho mỗi sân (field thì dễ hơn, yard thì áp dụng cho từng sân riêng), thường thì khung giờ ở mỗi field là giống nhau để dễ quản lí, và khung giờ này chỉ là giúp viêuc đặt sân đúng và dễ hơn (ví dụ khi đặt sân có cái select là lấy dữ liệu ở đây) chứ k có mục đích biết đc sân giờ đó đc đặt hay chưa (vì như a nói ở cmt trc là có thể đặt ở ngày khác nên cái này k chính xác)
Còn về 2 bảng calendar và day a thấy hơi nhập nhằng rồi, mình chỉ cần một bảng order là làm tốt việc này rồi, trong order mình lưu sân, ngày giờ đặt, thông tin người đặt, như vậy lúc query để xem danh sách sân trống theo ngày rất dễ, còn muốn xem một sân còn lịch trống ko cũng đơn giản

**Comment by ba-ppp** [comment]
![image](https://user-images.githubusercontent.com/60724808/85017086-1d6abf80-b195-11ea-841a-6bf5b3965fe1.png)

**Comment by ba-p** [comment]
nếu v là khi mình muốn xem sân nào trống là mình phải tìm trong `Order` id của sân ròi ngày trùng với ngày hiện tại ròi sắp giờ hả a :)))

**Comment by duysmile** [comment]
Ok em anh thấy vậy khá ok rồi đó, mà bảng yard với bảng order em thêm field owner nữa để lúc query hoặc check đk sẽ dễ hơn

**Comment by ba-ppp** [comment]
![image](https://user-images.githubusercontent.com/60724808/85039851-56fdf380-b1b2-11ea-89c1-cd17dbaae3e0.png)

**Comment by ba-ppp** [comment]
oke r a

**Comment by ba-ppp** [comment]
e tạo xong database mẫu trên cloudmongo luôn ròi nha

**Comment by ba-ppp** [comment]
Done nha mn
