### ISSUE TITLE
Tạo base source

### ISSUE THREAD

**Issue by duysmile** [duysmile/football-pitch-booking#4]
- [x] Client
- [x] Server

**Comment by ntdo2506** [comment]
@ba-p  e vẫn chưa làm cái ni ak hả

**Comment by ba-ppp** [comment]
sr a tối qua e đi học về trễ quá nên ch làm kịp giờ e làm đây

**Comment by ntdo2506** [comment]
> sr a tối qua e đi học về trễ quá nên ch làm kịp giờ e làm đây

ừ e làm xong nhớ tạo sandbox team hỉ...a nhận làm phần logic trước

**Comment by ba-ppp** [comment]
Done nha mn
